### ISSUE TITLE
Unsetting custom nvim binary does not work

### ISSUE THREAD

**Issue by p3palazzo** [qvacua/vimr#1022]
Expected behavior: Deleting the contents of the `Settings > Advanced > Neovim Binary` text field should unset the custom nvim binary.

Actual behavior: The settings reverts to the last contents of the Neovim Binary field. Only manually editing the `~/Library/Preferences/com.qvacua.VimR.plist` file manages to unset this customization.

Additionally, using the Homebrew nvim binary version 0.9.4 as the custom Neovim Binary does not work and results in a blank window in vimr.

Version 0.45.0 (20231122.130444)

**Comment by georgeharker** [comment]
Thanks for the report. That should be throwing up an alert saying incompatible version (upstream fixes were needed for this to work which are in newer versions) can you let me know if that alert shows. We will look at why unsettling doesn’t work.

**Comment by zornme** [comment]
I am having the same issue and wanted to chime in to say that the alert does not show. VimR hangs at load and then after a few seconds displays the blank screen. I've attached a screenshot as well. Thank you for all of your work on this project.

<img width="830" alt="image" src="https://github.com/qvacua/vimr/assets/129336/46f1acdd-0624-4761-9472-9e7aa1a54ee3">

**Comment by p3palazzo** [comment]
Exactly, that's my experience, too. No alert and just the blank window after a few seconds at startup.

**Comment by qvacua** [comment]
I'm afraid, I cannot reproduce the issue. I'm not sure, but, I made a [small change](https://github.com/qvacua/vimr/commit/a183ac2704e7c3fbbbe6192b7a57f76c67417b37) which might fix the issue. Can you please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F20231129.173509 ?

**Comment by qvacua** [comment]
BTW: @p3palazzo : Which version of macOS are you using?

**Comment by p3palazzo** [comment]
Ventura with the latest updates applied.

**Comment by qvacua** [comment]
@p3palazzo : My guess is that I could not reproduce it due to a subtle difference between macOS versions; I'm on Sonoma. If my guess is right, the new snapshot above should fix the issue: Please try it.

**Comment by p3palazzo** [comment]
Now it clears the path to the incompatible nvim binary on quit and relaunch, which solves the blank window problem, but still doesn't throw any alert.

**Comment by georgeharker** [comment]
I’ll take a look at the alert side.

**Comment by georgeharker** [comment]
I have some fixes for getting an incompatible version alert to show (it's a bit complex as older neovim without the upstream fix we submitted will block io until a connection is made on stdin, but we should have something soon.

**Comment by qvacua** [comment]
https://github.com/qvacua/vimr/releases/tag/v0.45.1-20231211.195158 contains the fix.
