### ISSUE TITLE
coc.nvim causes vimr to instantly close the window

### ISSUE THREAD

**Issue by lukad** [qvacua/vimr#768]
With the following minimal `.vimrc`, where only coc.nvim is enabled via vim-plug, the VimR window is closed right after starting the app. It doesn't crash, it still sits running in the dock, but when I click the app icon it shows for less than a second and is closed again.

```
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
```

Is there any way at all to get VimR to give me anything like a log file?

I'm using Version 0.29.0-329 installed via brew on Catalina 10.15.1.

**Comment by eyalk5** [comment]
It doesn't do this for me. Instead, it hangs when I use coc-vimtex. I mean when I type anything and press ESC. not sure how to debug. CocLog (on debug) is quite useless.

**Comment by eyalk5** [comment]
It only happens in vimr and not in nvim (0.5 at least)

**Comment by lukad** [comment]
Is there any more info I should provide to help get this fixed? Looks like I'm not the only one having this problem.

**Comment by shanesmith** [comment]
For what it's worth, I only started seeing this after I upgraded from Mojave (10.14) to Catalina (10.15)

**Comment by metalelf0** [comment]
I'm having the same issue.

**Comment by imajes** [comment]
I'm seeing this also, but only in .29 -- .28 doesn't have this same issue.

**Comment by mrinterweb** [comment]
Same issue here. 0.29 crashes immediately with coc. I don't know how to access crash logs. My coc config is pretty minimal. Good to know I'm not the only one with this problem.

**Comment by qvacua** [comment]
I'll look into it, but it will take some time. Currently, my free time is somewhat limited. :(

**Comment by qvacua** [comment]
Hm.. I cannot reproduce this issue. I did the following:

* Delete `~/.vim`
* Replace my `~/.config/nvim/init.vim` with the minimal config of @lukad 
* Open VimR and do `PlugInstall`
* Close the VimR window and open another VimR window.

I'm on 10.15.2 (and using node 13.6.0 and yarn 1.21.0).

**Comment by metalelf0** [comment]
> Hm.. I cannot reproduce this issue. I did the following:
> 
> * Delete `~/.vim`
> * Replace my `~/.config/nvim/init.vim` with the minimal config of @lukad
> * Open VimR and do `PlugInstall`
> * Close the VimR window and open another VimR window.
> 
> I'm on 10.15.2 (and using node 13.6.0 and yarn 1.21.0).

Tried it right now on 10.15.2, node 13.1.0 and yarn 1.21.1. Right after entering `:PlugInstall` the plugin installation caused the program to quit. It left a `vimr` application open, but cmd-alt-tabbing to it causes a vimr instance to pop up and immediately close, exactly as reported in the issue. Installed node 13.6.0 with nvm, switched to it, re-did the whole setup, and I still see the issue. Vimr version is 0.29.0-p329.

**Comment by metalelf0** [comment]
Edit: the issue is solved in latest snapshot `SNAPSHOT-332`.

**Comment by mrinterweb** [comment]
I see exactly what @metalelf0 saw with snapshot 332. I tried an empty Coc configuration file, and VimR still hangs. I am installing coc with: `Plug 'neoclide/coc.nvim', {'branch': 'release'}`. I'm not doing any other config. I can't think of anything in my config that could be different than the default config.
When Coc installs, it compiles its `maple` and `python dynamic` modules with rust. Not sure if there is a conflict happening between the compiled binaries and VimR.

I did get a stack trace from VimR so maybe this will help https://gist.github.com/mrinterweb/dabf6d575a9abb7b7a82e462aa465503

**Comment by qvacua** [comment]
I did not know coc.nvim until now, but it's awesome. I now must fix this bug... :)

**Comment by qvacua** [comment]
I could reproduce the issue (as described by @metalelf0). The problem was some code-signing issue. TBH, I don't know why there was a problem and why it is fixed now by https://github.com/qvacua/vimr/commit/765f2c43d7c2396f64f85dd08565c045ed9dbeaf. Please try [SNAPSHOT-334](https://github.com/qvacua/vimr/releases/tag/snapshot%2F334).

**Comment by shanesmith** [comment]
Works for me! ⭐️

**Comment by mrinterweb** [comment]
Thank you for this fix. Good to be using vimr again.
